# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      - name: PowerShell script
      #SCA Powershell Script
        $env:SRCCLR_API_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTU2NDQ4LCJleHAiOjE1OTM2MTM2NTEsImF1dGhvcml0aWVzIjoiQUdFTlQiLCJqdGkiOiJiZGI4OTJlZi01ZjM3LTQ0ZDYtODUxYi0wMzhlZWQ5ZDMwM2MiLCJjbGllbnRfaWQiOiIiLCJzY29wZSI6W119.LpFZZHscFI9tNgnz15ifUj-iEpVZD6Kqif3V7EIuvmeLewvAoWBIZIM6-5x_2MWj3lZP-fQZuqSvj6vrh7EMO3hayFAyahW1F-z9_eW3u6wwJQ5N4LBUZRyjbPs_2Yi0kKtar11iSESpa47J5Sbr-ZNFa3ay3gtcjrtGYVYvgxE"
        Set-ExecutionPolicy AllSigned -Scope Process -Force
        iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
        srcclr scan . 
    # PowerShell script to execute in Actions-hydrated context
    script: 
    - name: Veracode Upload And Scan
      # You may pin to the exact commit or the version.
      # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
      uses: veracode/veracode-uploadandscan-action@0.2.1
      with:
        # appname
        appname: 'Build System Demo Application'
        # createprofile
        createprofile: false
        # filepath
        filepath: target/*.war
        # version
        version: ${{ github.run_id }}
        # vid
        vid: ***
        # vkey
        vkey: ***
        # true or flase
        createsandbox: true
        # name of the sandbox
        sandboxname: 'GitHub-Build'
        # wait X minutes for the scan to complete
        scantimeout: # optional
        # modules to exclude from module selection
        exclude: # optional
        # modules to include in module selection
        include: # optional
        # business criticality - policy selection
        criticality: # optional
        # filename pattern
        pattern: # optional
        # replacement
        replacement: # optional
        # replacement
        sandboxid: # optional
        # All top level modules
        scanallnonfataltoplevelmodules: # optional
        # platform selected modules
        selected: # optional
        # selected modules like from previous scan
        selectedpreviously: # optional
        # teams
        teams: # optional
        # teams
        toplevel: # optional
